[package]
name = "message_board"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.30.0"
crossterm = "0.29.0"
chrono = "0.4.43"
rand = "0.9.2"

[[bin]]
name = "client"

[[bin]]
name = "server"

[profile.profiling]
inherits = "release"
debug = true