[package]
name = "message_board"
version = "0.1.0"
edition = "2024"

[dependencies]
termwiz = { version = "0.23.3", features = ["widgets"] }

[dev-dependencies]
rand = "0.9.2"

[[bin]]
name = "client"

[[bin]]
name = "server"

[profile.profiling]
inherits = "release"
debug = true